[project]
name = "telegram-bot"
version = "0.1.0"
description = "my first telegram bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.1",
]
